### ISSUE TITLE
Crash on isProbablyImage method in Filepicker

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#63]
I'm seeing this crash in FilePicker 3.8.0 on various  Samsung, LG, HTC devices. The stacktrace was collected through Crashlytics. 

java.lang.StringIndexOutOfBoundsException: length=107; regionStart=104; regionLength=-9
       at java.lang.String.startEndAndLength(String.java:588)
       at java.lang.String.substring(String.java:1475)
       at java.net.DefaultFileNameMap.getContentTypeFor(DefaultFileNameMap.java:38)
       at java.net.URLConnection.guessContentTypeFromName(URLConnection.java:681)
       at io.filepicker.models.Node.isProbablyImage(Node.java:60)
       at io.filepicker.adapters.NodesAdapter.getItemViewType(NodesAdapter.java:133)
       at android.widget.AbsListView$RecycleBin.getScrapView(AbsListView.java:7240)
       at android.widget.AbsListView.obtainView(AbsListView.java:2423)
       at android.widget.GridView.onMeasure(GridView.java:1044)
       at android.view.View.measure(View.java:16736)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16736)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16736)

**Comment by maciejwitowski** [comment]
Should not occur in version 3.8.1
