### ISSUE TITLE
Crash getTypedFileFromUri

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#64]
Have seen this crash a couple times on multiple versions of FilePicker. Currently I am using 3.8.0

This crash is from an HTC One(m7). 

java.lang.NullPointerException: mimeType
       at retrofit.mime.TypedFile.<init>(TypedFile.java:42)
       at io.filepicker.utils.FilesUtils.getTypedFileFromUri(FilesUtils.java:39)
       at io.filepicker.services.ContentService.handleActionUploadFile(ContentService.java:163)
       at io.filepicker.services.ContentService.onHandleIntent(ContentService.java:108)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by maciejwitowski** [comment]
I've checked it using Genymotion's HTC One (with android 4.3) but couldn't get this error.

Anyway,I changed it in a way that instead of the crash, there will be information to the user that the error has occurred (as with any other error in library). Still, if you have any tips how to reproduce this bug I will appreciate it - maybe there is more I can do about it.
