### ISSUE TITLE
OkHttp and Retrofit Exceptions

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#70]
Hello, I'm seeing some exceptions related to both libraries. I dont think these crashes actually happen on the latest versions of these libraries. I think they end up being treated as "RerofitError" instead of making apps crash. Have you considered upgrading?

      compile 'com.squareup.retrofit:retrofit:1.9.0'
      compile 'com.squareup.okhttp:okhttp:2.2.0'
      compile 'com.squareup.okhttp:okhttp-urlconnection:2.2.0'
     

Its probably also worth upgrading Picasso to 2.5.0, with retrofit 1.9.0 and picasso 2.5.0 you no longer need the okhttp-urlconnection shim dependency. 

Here are the crashes I'm seeing:

retrofit.RetrofitError: Unable to resolve host "dialog.filepicker.io": No address associated with hostname
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy11.pickFile()

retrofit.RetrofitError: timeout
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy19.pickFile()
       at io.filepicker.services.ContentService.handleActionPickFiles(ContentService.java:151)
       at io.filepicker.services.ContentService.onHandleIntent(ContentService.java:112)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.io.InterruptedIOException: timeout

**Comment by maciejwitowski** [comment]
I've updated it today and just pushed to maven, version 3.8.4

**Comment by Prashant6001** [comment]
retrofit.RetrofitError: 401 Unauthorized, i am geting this dialog error. please tell me how to solve this.
